### ISSUE TITLE
wpkba.com or wpkbarticles.com

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#50]
I'd like to discuss which of these domains we'd like to use as the primary, and what we might we might do with the other.

My preference would be wpkba.com for the primary domain because it is shorter/easier.

**Comment by brucewsinc** [comment]
> My preference would be wpkba.com for the primary domain because it is shorter/easier.
This is my preference as well.

**Comment by raamdev** [comment]
I initially thought `wpkba.com` would be better (because it's shorter), but then I realized that `wpkbarticles.com` is quite literally the name of the plugin, i.e., WP KB Articles → WPKBArticles.com, so how does it get any better than that? Also, while it's obvious and easy for us to realize that `WPKBA == WP KB Articles`, it might not be so obvious to others (especially anyone with a different native language).

Anyway, just some thoughts I had.

I do like that `wpkba.com` is shorter, but when I look at `wpkba.com`, I don't see anything that makes me think "Oh! KB Articles for WordPress!", as I do when I see `wpkbarticles.com`.

---

If we went with `wpkbarticles.com` for the plugin, what would I do with `wpkba.com`? I would use it as a KB Article URL shortener for all the KBs for our projects... so instead of `http://zencache.com/kb-article/questions-4-recommended-nginx-config/`, we could have `http://wpkba.com/KhpsP`; all of our projects that use WP KB Articles could use the shortener for their KB Articles...

**Comment by raamdev** [comment]
### Notes from 2015-01-27 Team Meeting

@brucewsinc writes...
> Personally, I just really like to see a short url whenever I visit a website. So I'm really biased towards wpkba.com myself.

@jaswsinc writes... 
> I like them both. I read your comments about the benefits of having the full name. I think they both have something to offer in terms of what is the better choice. It's an even match in my view. Having `kbarticles` in the domain is going to help SEO a bit, while `wpkba.com` is going to help the product image in my opinion. I say go with wpkbarticles.com and hang on to `wpkba.com` and use it some creative ways. Raam's idea for a URL shortener is not bad. Who knows, we may have another use for this too, or three or four.

@raamdev writes...
> I should add that I'm fine with `wpkba.com` myself; i.e., it won't bother me if that's what we went with. I re-read my comments on the GitHub Issue and I feel like I didn't give the `wpkba.com` idea enough credit. If it was my project, I'd pick `wpkbarticles.com` simply because it's the easiest to remember (once you know the name of the plugin), but either way is totally fine with me!
> 
> So have we agreed on `wpkbarticles.com`? :D

@jaswsinc writes... 
> lol ~ I'm voting for that one also now. I am imagining Google search results for: "WordPress KB Articles" and the domain `http://wpkbarticles.com/` is going to push us to the top much easier than with the shorter domain.

@brucewsinc writes... 
> Sounds fine to me. You guys know better.

@jaswsinc writes... 
> It will look just as impressive if we use `wpkba.com` as a shortlink for every post on the site; i.e. in our blog and in our KB for the KB

@raamdev writes...
> That's what I was thinking.

## Decision: wpkbarticles.com
