### ISSUE TITLE
TOC Text Overflow

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#56]
@raamdev writes...

>  Also keep in mind that a "Table of Contents" for those headers will likely be generated and shown alongside the KB article, so keeping those heading short and descriptive, so as to make navigating via the TOC easier.

@jaswsinc writes...

> I think it would be good to use a text overflow on the TOC to keep it looking nice, while not limiting us in terms of how long a heading can be. If I have a heading that reads, "Updating EOT Time"... for the purpose of SEO, I can change that to, "Updating Member EOT Time in WordPress Dashboard". That's going to be more attractive in a search engine, while not bringing the value of the article down. That would look worse in a TOC, but we could make adjustments to help improve that. Anyway, just a thought.

![2015-01-22_23-00-55](https://cloud.githubusercontent.com/assets/1563559/5871493/cea31f4c-a28a-11e4-954b-94a26cb0564a.png)

**Comment by raamdev** [comment]
If we could add the full title to the tool tip (maybe use the `title=""` attribute on the anchor tag?), that would also be very helpful. That way, someone can hover over the shortened link to see what the full title was.

Instead of that, we could make it dynamic so that hovering over a shortened title displays the full thing, but I'm not sure if the UX for that would just be annoying (titles hiding and expanding as the mouse rolls over them...).

**Comment by jaswsinc** [comment]
> If we could add the full title to the tool tip (maybe use the title="" attribute on the anchor tag?)

Cool! I agree, that would be nice.

**Comment by jaswsinc** [comment]
I'd call this ready to work on now. I'll go ahead and change the state on Waffle so it moves over to the Ready column.

NOTE: It seems like it would be nice to post screenshots as work begins on this and gather additional team feedback at that time in an effort to tune this in.
